export const ORDER_STATUS_LABELS_COLORS = {
  IN_PROGRESS: "#F7AD51",
  SUCCESS: "#00956D",
  CANCELLED: "#B6B7B9",
  FAILED: "#DF1638",
} as const;

export const REQUEST_STATUS_LABELS_COLORS = {
  NEW: "grey",
  IS_CONSIDERED: "#F7AD51",
  CLOSED: "#DF1638",
  SUCCESSFUL: "#00956D",
} as const;
