export const countryDeliveryConfig = [
  { name: "poland", comission: 6.38 },
  { name: "hungary", comission: 3.38 },
  { name: "greece", comission: 5.38 },
  { name: "ireland", comission: 6.38 },
  { name: "italy", comission: 7.38 },
  { name: "latvia", comission: 8.38 },
  { name: "luxembourg", comission: 12.38 },
  { name: "netherlands", comission: 8.38 },
  { name: "romania", comission: 8.38 },
  { name: "slovenia", comission: 7.38 },
  { name: "france", comission: 9.38 },
  { name: "czech", comission: 8.38 },
  { name: "austria", comission: 9.38 },
  { name: "bulgaria", comission: 9.38 },
  { name: "germany", comission: 10.38 },
  { name: "spain", comission: 8.38 },
  { name: "cyprus", comission: 10.38 },
  { name: "lithuania", comission: 8.38 },
  { name: "portugal", comission: 6.38 },
  { name: "slovakia", comission: 9.38 },
  { name: "finland", comission: 5.38 },
  { name: "sweden", comission: 5.38 },
  { name: "croatia", comission: 6.38 },
];
